name: Generate Cyberpunk Commit Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Cyberpunk SVG
        uses: Platane/snk@v3
        with:
          github_user_name: SEU_USUARIO
          outputs: |
            dist/cyberpunk.svg?palette=github-dark
            &color_snake=#8A2BE2
            &color_dots=#00FFFF,#FF00FF,#00FF7F,#FFD700
            &background=#0D1117

      - name: Push animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
